site_name: spiderpool
docs_dir: docs
site_dir: site
repo_name: spidernet-io/spiderpool
repo_url: https://github.com/spidernet-io/spiderpool
remote_branch: github_pages
theme:
  name: readthedocs
  # The maximum depth of the navigation tree in the sidebar
  navigation_depth: 2
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share

plugins:
  - tags
  - search

markdown_extensions:
  - meta
  - toc
  - tables
  - fenced_code
  - tables
  - attr_list
