name: main

on:
  push:
    branches:
      - main
env:
  KUKEAN_OPERATOR_IMAGE_NAME: kubean-operator
  SPRAY_JOB_IMAGE_NAME: spray-job
jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: kubean-operator Build image
        run: docker build . --file ./build/images/kubean-operator/Dockerfile --tag $KUKEAN_OPERATOR_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: kubean-operator Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$KUKEAN_OPERATOR_IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(git describe --tags --abbrev=8 --dirty)
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $KUKEAN_OPERATOR_IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $KUKEAN_OPERATOR_IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
      - name: spray-job Build image
        run: docker build . --file ./build/images/spray-job/Dockerfile --tag $SPRAY_JOB_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: spray-job Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$SPRAY_JOB_IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(git describe --tags --abbrev=8 --dirty)
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $SPRAY_JOB_IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $SPRAY_JOB_IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
