name: pr

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: static check
        uses: golangci/golangci-lint-action@v3
        with: 
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.46.2

      - name: unit test
        run: ls
